login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('check', views.check, name='check'),
    path('formpage/', views.form_one, name='form_name'),
    path('snippet/', views.snippet_detail, name='snippet_detail')
]

myfirstdjangoproject/urls.py
from django.conf.urls import include
from django.contrib import admin
# from django.conf.urls import url
from django.urls import path
from account import views
# from basic_app import views
# from polls import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('', views.dashboard),

    # url('polls/', views.detail),
    path('polls/', include('polls.urls')),

    path('account/', include('account.urls')),

    path('userlogin/', include('userlogin.urls')),

    path('basic_app/', include('basic_app.urls')),
    # path('logout/', views.user_logout)
    # path('special/', views.special)

    # only one call on app_urls
    # url('', views.detail),
    # url('', views.results),
    # url('', views.vote),

]

login/forms.py
from random import choices

from django import forms

from login.models import Snippet


class FormName(forms.Form):
    name = forms.CharField(label='name', max_length=20, widget=[])
    subject = forms.CharField(max_length=10)
    # category = forms.ChoiceField(choices=[('question', 'Question'), ('other', 'Other')])
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ('name', 'subject', 'email')

templates/check.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form>
    <h1>Login Form</h1>
     Enter your User_Name: <input type="text" name="username" placeholder="your user_name..."><br>
    Enter your Password: <input type="password" name="password" placeholder="your password..."><br>
    <input type="submit">
</form>
</body>
</html>

templates/form_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form Page</title>
</head>
<body>

<div class="container">
    <form action="{% url 'form_name' %}" method="post">
        {% csrf_token %}
{#        {{ form.as_ul }}#}
        <ul style="list-style: none">
            <li> <label for="name">Name:
                <input id="name" type="text" name="name" maxlength="100" required value="{{ current_name }}"></label></li><br>
            <li><label for="id_subject">Subject:
                <input id="id_subject" type="text" name="subject" maxlength="10" required value="{{ current_subject }}"></label></li><br>
            <li><label for="id_message">Message:<textarea name="message" id="id_message" required></textarea></label></li><br>
            <li><label for="id_sender">Sender:</label><input type="email" name="sender" id="id_sender" required></li><br>
            <li><label for="id_cc_myself">Cc myself:</label><input type="checkbox" name="cc_myself" id="id_cc_myself"></li><br>
            <li><input type="submit" class="btn btn-primary" value="Submit"></li>
        </ul>
{#        <input type="submit" class="btn btn-primary" value="Submit">#}
    </form>

</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<form method="post" action="{% url 'index' %}" style="border: 1px solid;">
    <center>
    <h1> Registration Form</h1>
    Enter your User_Name: <input type="text" name="username" placeholder="your user_name..."><br><br>
    Enter your Password: <input type="password" name="password" placeholder="your password..."><br><br>
    Enter your First_Name: <input type="text" name="first_name" placeholder="your first_name..."><br><br>
    Enter your Last_Name: <input type="text" name="last_name" placeholder="your last_name..."><br><br>
    <input type="submit"><br></center>
    </form>
</body>
</html>

templates/model_field.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Model Field</title>
</head>
<body>
    <form action="{% url 'snippet_detail' %}" method="POST">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</body>
</html>